# Numpy

`NumPy` es una librería para hacer computos numéricos en Python. Es la base de muchas otras librerías científicas. Entre otras cosas, nos permite:

- Utilizar arreglos multidimensionales.
- Utilizar funciones matemáticas.
- Utilizar herramientas de álgebra lineal.

Necesitamos conocer esta librería (en concreto, el manejo de arreglos) para poder entender el funcionamiento de `pandas`.

### Requisitos

Para esta clase necesitamos tener instalada la librería numpy:

```
pip3 install --upgrade numpy
```

Para comenzar a trabajar vamos a importar la librería y crear un pequeño arreglo de elementos aleatorios.

In [1]:
import numpy as np
np.random.seed(0)
data = np.random.randn(2,4)
data

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721]])

In [7]:
print(data)

[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]]


In [2]:
#miremos una lista de python
l=[1,2,3,4,5]

In [8]:
l

[1, 2, 3, 4, 5]

In [9]:
print(l)

[1, 2, 3, 4, 5]


In [3]:
h=l*10

In [4]:
h

[1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5]

A diferencia de una lista, podemos hacer operaciones matriciales, como multiplicar el arreglo `data` por un escalar:

In [10]:
data*10

array([[17.64052346,  4.00157208,  9.78737984, 22.40893199],
       [18.6755799 , -9.7727788 ,  9.50088418, -1.51357208]])

o sumarle una matriz:

In [11]:
data + data

array([[ 3.52810469,  0.80031442,  1.95747597,  4.4817864 ],
       [ 3.73511598, -1.95455576,  1.90017684, -0.30271442]])

In [12]:
l+l

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

### Crear arreglos

Podemos crear arreglos a partir de una lista:

In [16]:
data1 = [1, 1, 2, 3, 5]
arr1 = np.array(data1)
print(data1)
print(arr1)
print(type(data1))
print(type(arr1))
print(arr1.shape)

[1, 1, 2, 3, 5]
[1 1 2 3 5]
<class 'list'>
<class 'numpy.ndarray'>
(5,)


In [17]:
#un arreglo de (5,) es igual a un arreglo de (1,5)
arr1R=arr1.reshape(1,5)

In [15]:
print(arr1R)
print(type(arr1R))
print(arr1R.shape)

[[1 1 2 3 5]]
<class 'numpy.ndarray'>
(1, 5)


In [19]:
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 1 2 3 5]
<class 'numpy.ndarray'>
(5,)


In [20]:
print(arr1.ndim)
print(arr1R.ndim)

1
2


In [21]:
arr1.shape

(5,)

In [22]:
arr1.size

5

In [23]:
len(arr1)

5

In [24]:
arr1R.shape

(1, 5)

In [25]:
arr1R.size

5

In [26]:
len(arr1R)

1

In [27]:
len(arr1R[0])

5

In [28]:
data2 = [[1, 1, 2, 3], [5, 8, 13, 21]]
arr2 = np.array(data2)
arr2

array([[ 1,  1,  2,  3],
       [ 5,  8, 13, 21]])

Para preguntar el número de dimensiones utilizamos `ndim`. Para preguntar las dimensiones utilizamos `shape`.

In [29]:
arr2.size

8

In [30]:
arr2.shape

(2, 4)

In [31]:
len(arr2)

2

### Accediendo a elementos

Para obtener un elemento:

In [ ]:
arr1

array([1, 1, 2, 3, 5])

In [ ]:
arr1[2]

2

In [32]:
arr2

array([[ 1,  1,  2,  3],
       [ 5,  8, 13, 21]])

In [33]:
arr2[1][2]

13

In [34]:
# Podemos acceder de esta forma también.
arr2[1, 2]

13

Los arreglos son mutables (su contenido puede ser cambiado despues de haber sido creado):

In [35]:
arr1[3] = 300
arr1

array([  1,   1,   2, 300,   5])

In [36]:
arr2[1, 2] = 100
arr2

array([[  1,   1,   2,   3],
       [  5,   8, 100,  21]])

### arange

También tenemos un equivalente a `range` llamado `arange`, pero que genera un arreglo.

In [37]:
np.arange(2, 11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

### Operaciones sobre arreglos

Algunas operaciones que se pueden hacer sobre un arreglo son:

In [38]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
arr * arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [40]:
arr + 1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [41]:
(arr + 1) - arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [42]:
1 / arr

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [ ]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

### _Slices_

Podemos extraer partes de un arreglo tal como en las listas. También podemos usar esto para cambiar los valores de dichos elementos.

In [43]:
arr = np.arange(3,15)
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
arr[3:6]

array([6, 7, 8])

In [45]:
arr[3:6] = 1
arr

array([ 3,  4,  5,  1,  1,  1,  9, 10, 11, 12, 13, 14])

### Indexando con booleanos

Podemos utilizar comparaciones booleanas con los arreglos:

In [46]:
arr = np.array([0, 0, 1, 1, 2, 2])
arr == 1

array([False, False,  True,  True, False, False])

Y usarlo para acceder a valores en otros arreglos. Vamos a crear un arreglo multidimensional e ingresar el arreglo anterior como índice:

In [47]:
arr2 = np.random.randn(6, 3)
arr2

array([[-0.10321885,  0.4105985 ,  0.14404357],
       [ 1.45427351,  0.76103773,  0.12167502],
       [ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567]])

In [49]:
arr2[arr == 1]

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574]])

Y también podemos negar la condición:

In [50]:
arr2[~(arr == 1)]

array([[-0.10321885,  0.4105985 ,  0.14404357],
       [ 1.45427351,  0.76103773,  0.12167502],
       [-2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567]])

### Transponer un arreglo

Es posible obtener la transpuesta de un arreglo rápidamente.

In [51]:
arr = np.random.randn(6, 3)
arr

array([[ 0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985],
       [-0.38732682, -0.30230275, -1.04855297],
       [-1.42001794, -1.70627019,  1.9507754 ]])

In [52]:
arr.T

array([[ 0.04575852,  1.46935877, -0.88778575,  0.15634897, -0.38732682,
        -1.42001794],
       [-0.18718385,  0.15494743, -1.98079647,  1.23029068, -0.30230275,
        -1.70627019],
       [ 1.53277921,  0.37816252, -0.34791215,  1.20237985, -1.04855297,
         1.9507754 ]])

### Otras funciones

Tenemos acceso a algunas funciones de estadística básicas. Por ejemplo `sum`, `mean` y `std` nos permiten respectivamente sacar la suma, el promedio y la desviación estándar de un arreglo.

In [53]:
arr = np.random.randn(10)
arr

array([-0.50965218, -0.4380743 , -1.25279536,  0.77749036, -1.61389785,
       -0.21274028, -0.89546656,  0.3869025 , -0.51080514, -1.18063218])

In [54]:
arr.sum()

-5.4496710003784745

In [55]:
arr.mean()

-0.5449671000378474

In [56]:
arr.std()

0.7008597108858429

También podemos ordenar:

In [58]:
# Ordenar de menor a mayor
arr.sort()
arr

array([-1.61389785, -1.25279536, -1.18063218, -0.89546656, -0.51080514,
       -0.50965218, -0.4380743 , -0.21274028,  0.3869025 ,  0.77749036])

In [60]:
# Ordenar de  mayor a menor
arr.sort()
arr[::-1]    # Invertir el arreglo


array([ 0.77749036,  0.3869025 , -0.21274028, -0.4380743 , -0.50965218,
       -0.51080514, -0.89546656, -1.18063218, -1.25279536, -1.61389785])

Y pedir elementos distintos:

In [61]:
arr = np.array([0, 0, 1, 1, 2, 2])
np.unique(arr)

array([0, 1, 2])

In [62]:
#inversa de un arreglo
x = np.array([[1,2],[3,4]])
y = np.linalg.inv(x)


In [ ]:
y